In [1]:
#imports required in the notebook
import pandas as pd
import numpy as np

### NumPy

In [2]:
#Creating an array using Numpy
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))  #type of array

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
print(np.ones(4))      #array of one's
print(np.zeros(4))     #array of zero's

[1. 1. 1. 1.]
[0. 0. 0. 0.]


In [4]:
arr2=np.array([['a','b','c'],['d','e','f']])  #2D array
print(arr2)                 #printing the array
print(arr2.shape)           #priting the shape of array
print(arr2.size)            #printing the size(total number of elements) of array
print(arr2.ndim)             #printing the dimension of the array

[['a' 'b' 'c']
 ['d' 'e' 'f']]
(2, 3)
6
2


In [5]:
arr1 = np.array([4,4,4,4])
arr2 = np.array([2,2,2,2])
print(arr1+arr2) #addition
print(arr1-arr2) #subtraction
print(arr1*arr2) #multiplication
print(arr1/arr2) #division

[6 6 6 6]
[2 2 2 2]
[8 8 8 8]
[2. 2. 2. 2.]


In [6]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])
print(arr[0][1])
print(arr[0:2,0:3])

10
2
[[1 2 3]
 [6 7 8]]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(3,4))  #reshaping the array from 1-D to 3-D

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
arr = np.array([2,5,3,1,6,9,7,8,4])
arr.sort()  #sorting the array inplace ,You can also use np.sort(arr) to sort the array
print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
print(np.where(arr%2==0))   #Searching inside the array

(array([1, 3, 5, 7], dtype=int64),)


In [10]:
arr.searchsorted([10,11]) 

array([9, 9], dtype=int64)

### Pandas

In [11]:
cars = pd.read_csv("cars.csv",delimiter=';')

In [12]:
cars.head()  #printing the first 5 elements

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US

In [13]:
cars.tail()   #printing the last 5 elements

Car   MPG  Cylinders  Displacement  Horsepower  Weight  \
401    Ford Mustang GL  27.0          4         140.0        86.0  2790.0   
402  Volkswagen Pickup  44.0          4          97.0        52.0  2130.0   
403      Dodge Rampage  32.0          4         135.0        84.0  2295.0   
404        Ford Ranger  28.0          4         120.0        79.0  2625.0   
405         Chevy S-10  31.0          4         119.0        82.0  2720.0   

     Acceleration  Model  Origin  
401          15.6     82      US  
402          24.6     82  Europe  
403          11.6     82      US  
404          18.6     82      US  
405          19.4     82      US

In [14]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Car           406 non-null    object 
 1   MPG           406 non-null    float64
 2   Cylinders     406 non-null    int64  
 3   Displacement  406 non-null    float64
 4   Horsepower    406 non-null    float64
 5   Weight        406 non-null    float64
 6   Acceleration  406 non-null    float64
 7   Model         406 non-null    int64  
 8   Origin        406 non-null    object 
dtypes: float64(5), int64(2), object(2)
memory usage: 28.7+ KB


In [15]:
cars.describe()

MPG   Cylinders  Displacement  Horsepower       Weight  \
count  406.000000  406.000000    406.000000  406.000000   406.000000   
mean    23.051232    5.475369    194.779557  103.529557  2979.413793   
std      8.401777    1.712160    104.922458   40.520659   847.004328   
min      0.000000    3.000000     68.000000    0.000000  1613.000000   
25%     17.000000    4.000000    105.000000   75.000000  2226.500000   
50%     22.350000    4.000000    151.000000   93.500000  2822.500000   
75%     29.000000    8.000000    302.000000  129.000000  3618.250000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       Acceleration       Model  
count    406.000000  406.000000  
mean      15.519704   75.921182  
std        2.803359    3.748737  
min        8.000000   70.000000  
25%       13.700000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [16]:
series= pd.Series(cars["Car"])    #Series object
series  

0      Chevrolet Chevelle Malibu
1              Buick Skylark 320
2             Plymouth Satellite
3                  AMC Rebel SST
4                    Ford Torino
                 ...            
401              Ford Mustang GL
402            Volkswagen Pickup
403                Dodge Rampage
404                  Ford Ranger
405                   Chevy S-10
Name: Car, Length: 406, dtype: object

In [17]:
print(series[:10])  #printing first 10 elements using slicing

0    Chevrolet Chevelle Malibu
1            Buick Skylark 320
2           Plymouth Satellite
3                AMC Rebel SST
4                  Ford Torino
5             Ford Galaxie 500
6             Chevrolet Impala
7            Plymouth Fury iii
8             Pontiac Catalina
9           AMC Ambassador DPL
Name: Car, dtype: object


In [18]:
series.iloc[0:5]   #finding elements using .iloc

0    Chevrolet Chevelle Malibu
1            Buick Skylark 320
2           Plymouth Satellite
3                AMC Rebel SST
4                  Ford Torino
Name: Car, dtype: object

In [19]:
cars.loc[0:5]

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   
5           Ford Galaxie 500  15.0          8         429.0       198.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US  
5  4341.0          10.0     70     US

In [20]:
cars.iloc[1]

Car             Buick Skylark 320
MPG                            15
Cylinders                       8
Displacement                  350
Horsepower                    165
Weight                       3693
Acceleration                 11.5
Model                          70
Origin                         US
Name: 1, dtype: object

In [21]:
dict = {'First Score':[100, 90, None, 95], 
        'Second Score': [30, 45, 56, None], 
        'Third Score':[None, 40, 80, 98]}      #making a dict for a dataset

data = pd.DataFrame(dict)    #making a dataframe
data

First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [22]:
data.isnull()   #check missing values

First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [23]:
data.fillna("Not Null")   #using fillna() to replace the null values

First Score Second Score Third Score
0         100           30    Not Null
1          90           45          40
2    Not Null           56          80
3          95     Not Null          98

In [24]:
data.dropna()    #removes rows or coloums(depending on axis) containing null values

First Score  Second Score  Third Score
1         90.0          45.0         40.0